var dyes = [
['Purple Pinstripe Cloth', 4, 0],
['Brown Lined Cloth', 4, 1],
['Blue Striped Cloth', 5, 0],
['Black Striped Cloth', 5, 1],
['Rainbow Cloth', 9, 0],
['Starry Cloth', 9, 1],
['Brown Stitch Cloth', 10, 0],
['Tan Diamond Cloth', 10, 1],
['Green Weave Cloth', 10, 2],
['Blue Wave Cloth', 10, 3],
['Yellow Wire Cloth', 10, 4],
['Futuristic Cloth', 10, 5],
['Stony Cloth', 10, 6],
['Heart Cloth', 10, 7],
['Skull Cloth', 10, 8],
['Red Diamond Cloth', 10, 9],
['Jester Cloth', 10, 10],
['Crossbox Cloth', 10, 11],
['White Diamond Cloth', 10, 12],
['Grey Scaly Cloth', 10, 13],
['Red Spotted Cloth', 10, 14],
['Smiley Cloth', 10, 15],
['Bold Diamond Cloth', 10, 16],
['Blue Lace Cloth', 9, 2],
['Loud Spotted Cloth', 9, 3],
['Red Weft Cloth', 9, 4],
['Pink Sparkly Cloth', 9, 5],
['Red Lace Cloth', 9, 6],
['Pink Maze Cloth', 9, 7],
['Yellow Dot Cloth', 4, 2],
['Black Clothing Dye', 1, '#000000'],
['Dark Green Clothing Dye', 1, '#006400'],
['Dark Slate Gray Clothing Dye', 1, '#2f4f4f'],
['Maroon Clothing Dye', 1, '#800000'],
['Olive Clothing Dye', 1, '#808000'],
['Green Clothing Dye', 1, '#008000'],
['Teal Clothing Dye', 1, '#008080'],
['Navy Clothing Dye', 1, '#000080'],
['Purple Clothing Dye', 1, '#800080'],
['Indigo Clothing Dye', 1, '#4b0082'],
['Midnight Blue Clothing Dye', 1, '#191970'],
['Dark Red Clothing Dye', 1, '#8b0000'],
['Dark Cyan Clothing Dye', 1, '#008b8b'],
['Dark Blue Clothing Dye', 1, '#00008b'],
['Dark Magenta Clothing Dye', 1, '#8b008b'],
['Dark Olive Green Clothing Dye', 1, '#556b2f'],
['Saddle Brown Clothing Dye', 1, '#8b4513'],
['Forest Green Clothing Dye', 1, '#228b22'],
['Olive Drab Clothing Dye', 1, '#6b8e23'],
['Sea Green Clothing Dye', 1, '#2e8b57'],
['Dark Golden Rod Clothing Dye', 1, '#b8860b'],
['Dark Slate Blue Clothing Dye', 1, '#483d8b'],
['Sienna Clothing Dye', 1, '#a0522d'],
['Medium Blue Clothing Dye', 1, '#0000cd'],
['Brown Clothing Dye', 1, '#a52a2a'],
['Dark Turquoise Clothing Dye', 1, '#00ced1'],
['Dim Gray Clothing Dye', 1, '#696969'],
['Light Sea Green Clothing Dye', 1, '#20b2aa'],
['Dark Violet Clothing Dye', 1, '#9400d3'],
['Fire Brick Clothing Dye', 1, '#b22222'],
['Medium Violet Red Clothing Dye', 1, '#c71585'],
['Medium Sea Green Clothing Dye', 1, '#3cb371'],
['Chocolate Clothing Dye', 1, '#d2691e'],
['Crimson Clothing Dye', 1, '#dc143c'],
['Golden Rod Clothing Dye', 1, '#daa520'],
['Medium Spring Green Clothing Dye', 1, '#00fa9a'],
['Steel Blue Clothing Dye', 1, '#4682b4'],
['Lawn Green Clothing Dye', 1, '#7cfc00'],
['Dark Orchid Clothing Dye', 1, '#9932cc'],
['Red Clothing Dye', 1, '#ff0000'],
['Orange Red Clothing Dye', 1, '#ff4500'],
['Dark Orange Clothing Dye', 1, '#ff8c00'],
['Orange Clothing Dye', 1, '#ffa500'],
['Gold Clothing Dye', 1, '#ffd700'],
['Yellow Clothing Dye', 1, '#ffff00'],
['Yellow Green Clothing Dye', 1, '#9acd32'],
['Chartreuse Clothing Dye', 1, '#7fff00'],
['Lime Green Clothing Dye', 1, '#32cd32'],
['Lime Clothing Dye', 1, '#00ff00'],
['Spring Green Clothing Dye', 1, '#00ff7f'],
['Aqua Clothing Dye', 1, '#00ffff'],
['Cyan Clothing Dye', 1, '#00ffff'],
['Cadet Blue Clothing Dye', 1, '#5f9ea0'],
['Deep Sky Blue Clothing Dye', 1, '#00bfff'],
['Blue Clothing Dye', 1, '#0000ff'],
['Fuchsia Clothing Dye', 1, '#ff00ff'],
['Magenta Clothing Dye', 1, '#ff00ff'],
['Gray Clothing Dye', 1, '#808080'],
['Slate Gray Clothing Dye', 1, '#708090'],
['Peru Clothing Dye', 1, '#cd853f'],
['Blue Violet Clothing Dye', 1, '#8a2be2'],
['Light Slate Gray Clothing Dye', 1, '#778899'],
['Deep Pink Clothing Dye', 1, '#ff1493'],
['Medium Turquoise Clothing Dye', 1, '#48d1cc'],
['Dodger Blue Clothing Dye', 1, '#1e90ff'],
['Turquoise Clothing Dye', 1, '#40e0d0'],
['Royal Blue Clothing Dye', 1, '#4169e1'],
['Slate Blue Clothing Dye', 1, '#6a5acd'],
['Medium Orchid Clothing Dye', 1, '#ba55d3'],
['Dark Khaki Clothing Dye', 1, '#bdb76b'],
['Indian Red Clothing Dye', 1, '#cd5c5c'],
['Green Yellow Clothing Dye', 1, '#adff2f'],
['Medium Aqua Marine Clothing Dye', 1, '#66cdaa'],
['Tomato Clothing Dye', 1, '#ff6347'],
['Medium Purple Clothing Dye', 1, '#9370d8'],
['Pale Violet Red Clothing Dye', 1, '#d87093'],
['Orchid Clothing Dye', 1, '#da70d6'],
['Rosy Brown Clothing Dye', 1, '#bc8f8f'],
['Dark Sea Green Clothing Dye', 1, '#8fbc8f'],
['Coral Clothing Dye', 1, '#ff7f50'],
['Cornflower Blue Clothing Dye', 1, '#6495ed'],
['Dark Gray Clothing Dye', 1, '#a9a9a9'],
['Sandy Brown Clothing Dye', 1, '#f4a460'],
['Medium Slate Blue Clothing Dye', 1, '#7b68ee'],
['Tan Clothing Dye', 1, '#d2b48c'],
['Dark Salmon Clothing Dye', 1, '#e9967a'],
['Burly Wood Clothing Dye', 1, '#deb887'],
['Hot Pink Clothing Dye', 1, '#ff69b4'],
['Salmon Clothing Dye', 1, '#fa8072'],
['Light Coral Clothing Dye', 1, '#f08080'],
['Violet Clothing Dye', 1, '#ee82ee'],
['Sky Blue Clothing Dye', 1, '#87ceeb'],
['Light Salmon Clothing Dye', 1, '#ffa07a'],
['Khaki Clothing Dye', 1, '#f0e68c'],
['Plum Clothing Dye', 1, '#dda0dd'],
['Light Green Clothing Dye', 1, '#90ee90'],
['Aquamarine Clothing Dye', 1, '#7fffd4'],
['Silver Clothing Dye', 1, '#c0c0c0'],
['Light Sky Blue Clothing Dye', 1, '#87cefa'],
['Light Steel Blue Clothing Dye', 1, '#b0c4de'],
['Pale Green Clothing Dye', 1, '#98fb98'],
['Light Blue Clothing Dye', 1, '#add8e6'],
['Powder Blue Clothing Dye', 1, '#b0e0e6'],
['Thistle Clothing Dye', 1, '#d8bfd8'],
['Pale Golden Rod Clothing Dye', 1, '#eee8aa'],
['Pale Turquoise Clothing Dye', 1, '#afeeee'],
['Light Grey Clothing Dye', 1, '#d3d3d3'],
['Wheat Clothing Dye', 1, '#f5deb3'],
['Navajo White Clothing Dye', 1, '#ffdead'],
['Moccasin Clothing Dye', 1, '#ffe4b5'],
['Light Pink Clothing Dye', 1, '#ffb6c1'],
['Gainsboro Clothing Dye', 1, '#dcdcdc'],
['Peach Puff Clothing Dye', 1, '#ffdab9'],
['Pink Clothing Dye', 1, '#ffc0cb'],
['Bisque Clothing Dye', 1, '#ffe4c4'],
['Light Golden Rod Yellow Clothing Dye', 1, '#fafad2'],
['Blanched Almond Clothing Dye', 1, '#ffebcd'],
['Lemon Chiffon Clothing Dye', 1, '#fffacd'],
['Antique White Clothing Dye', 1, '#faebd7'],
['Beige Clothing Dye', 1, '#f5f5dc'],
['Papaya Whip Clothing Dye', 1, '#ffefd5'],
['Cornsilk Clothing Dye', 1, '#fff8dc'],
['Light Yellow Clothing Dye', 1, '#ffffe0'],
['Light Cyan Clothing Dye', 1, '#e0ffff'],
['Misty Rose Clothing Dye', 1, '#ffe4e1'],
['Linen Clothing Dye', 1, '#faf0e6'],
['Lavender Clothing Dye', 1, '#e6e6fa'],
['Old Lace Clothing Dye', 1, '#fdf5e6'],
['White Smoke Clothing Dye', 1, '#f5f5f5'],
['Sea Shell Clothing Dye', 1, '#fff5ee'],
['Floral White Clothing Dye', 1, '#fffaf0'],
['Ivory Clothing Dye', 1, '#fffff0'],
['Honey Dew Clothing Dye', 1, '#f0fff0'],
['Azure Clothing Dye', 1, '#f0ffff'],
['Alice Blue Clothing Dye', 1, '#f0f8ff'],
['Lavender Blush Clothing Dye', 1, '#fff0f5'],
['Mint Cream Clothing Dye', 1, '#f5fffa'],
['Ghost White Clothing Dye', 1, '#f8f8ff'],
['Snow Clothing Dye', 1, '#fffafa'],
['White Clothing Dye', 1, '#ffffff'],
// build 122
['Cloud Cloth', 9, 8],
['Glowthread Cloth', 5, 2],
['Sweater Cloth', 5, 3],
['Bee Stripe Cloth', 5, 4],
['Western Stripe Cloth', 4, 3],
['Blue Point Cloth', 4, 4],
['Robber Cloth', 4, 5],
['Chainmail Cloth', 4, 6],
['Dark Blue Stripe Cloth', 4, 7],
['Vine Cloth', 10, 17],
['Party Cloth', 10, 18],
['Viva Cloth', 10, 19],
['Nautical Cloth', 10, 20],
['Cactus Zag Cloth', 10, 21],
['Big-Stripe Blue Cloth', 10, 22],
['Big-Stripe Red Cloth', 10, 23],
['Starry Night Cloth', 10, 24],
['Lemon-Lime Cloth', 10, 25],
['Floral Cloth', 10, 26],
['Pink Dot Cloth', 10, 27],
['Dark Eyes Cloth', 10, 28],
['Wind Cloth', 10, 29],
// build 122.2
// ['Shamrock Cloth', 9, 9],
// ['St Patrick's Green Clothing Dye', 1, '#00cf00'],
// build 123.3.2
['Bright Stripes Cloth', 10, 30],
['USA Flag Cloth', 10, 31],
['Flannel Cloth', 10, 32],
['Cow Print Cloth', 10, 33],
['Lush Camo Cloth', 10, 34],
['Dark Camo Cloth', 10, 35],
['Teal Crystal Cloth', 10, 36],
['Blue Fireworks Cloth', 10, 37],
['Crisscross Cloth', 10, 38],
['Diamond Cloth', 10, 39],
['Egyption Cloth', 10, 40],
['Purple Bones Cloth', 10, 41],
['Plaid Cloth', 10, 42],
['Red USA Star Cloth', 9, 10],
['Blue USA Star Cloth', 9, 11],
['USA Star Cloth', 9, 12],
['Purple Stripes Cloth', 5, 5],
['Bright Floral Cloth', 5, 6],
// 4.0
['Clanranald Cloth', 10, 43],
['American Flag Cloth', 10, 44],
['Relief Cloth', 9, 13],
]
